### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by Qharny** [NIT-Academy/learning-resources#1]
# CSS FRAMEWORKS
```
So far i've seen only Javascript frameworks
I think it will be nice to consider the css frameworks( Tailwind, Bootstrap)
````

## UI/UX
```
It will be nice to add figma design as well
```

**Comment by Mark-Finley** [comment]
Yeah the framewsork is all inclusive, currently there is no resource in the repo.
UI/UX resources is not bad, let's discuss it further and see the way to go.

**Comment by Qharny** [comment]
Hello Sir, Been A hile since I've heard from you

________________________________
